### ISSUE TITLE
Hesai XT16 LiDAR

### ISSUE THREAD

**Issue by deniwaki** [tier4/nebula#137]
I want to use the XT16 in Nebula,　Is there a good way to do it?　
Or any update plan for use XT16 near future?

**Comment by mojomex** [comment]
Thank you for your interest in Nebula! Sadly, we are currently not supporting XT16 and do not currently have a model to test with.
However, seeing as the datasheets of XT32 and XT16 are (as far as I can tell) identical except for the 32 vs. 16 channels, it should be fairly quick to work off of the existing XT32 code to add support.
This would involve:
* Adding XT16 as a recognized model name in a few places (basically search and copy XT32)
* Adding an XT16 sensor definition (copy XT32)
* Perform testing (connect to the sensor, show pointcloud output)
* If everything looks good, record `/pandar_packets` while XT16 is running for us to confirm it is working.
* Add a unit test case based on the recorded packets

If you specifically want to use Nebula with XT16 and are willing to create a PR along those lines, we would be very happy to work with you on this.

**Comment by drwnz** [comment]
@deniwaki @jemmmel How did you get on with testing XT-16? If you managed to implement in Nebula, we'd be happy to review a PR. Otherwise, I'll close this issue as we have do not have access to a device to test at TIER IV.

**Comment by jemmmel** [comment]
Sorry, I have not had time to look at this lately. If I do, I will request to re-open it

**Comment by imeshsps** [comment]
I was able to do some modifications on XT32 implementation and get following outputs from XT16.
```
$ ros2 launch nebula_ros hesai_launch_all_hw.xml sensor_model:=PandarXT16

[INFO] [launch]: All log files can be found below /home/user/.ros/log/2024-11-28-10-38-10-647809-user-agx-orin-211950
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [hesai_ros_wrapper_node-1]: process started with pid [211951]
[hesai_ros_wrapper_node-1] [INFO] [1732770490.919271248] [hesai_ros_wrapper_node]: Sensor Configuration: Hesai Sensor Configuration:
[hesai_ros_wrapper_node-1] Sensor Model: PandarXT16
[hesai_ros_wrapper_node-1] Frame ID: hesai
[hesai_ros_wrapper_node-1] Host IP: 192.168.123.50
[hesai_ros_wrapper_node-1] Sensor IP: 192.168.123.20
[hesai_ros_wrapper_node-1] Data Port: 2368
[hesai_ros_wrapper_node-1] Return Mode: LastStrongest
[hesai_ros_wrapper_node-1] Frequency: 65535
[hesai_ros_wrapper_node-1] MTU: 1500
[hesai_ros_wrapper_node-1] Use Sensor Time: 0
[hesai_ros_wrapper_node-1] Multicast: disabled
[hesai_ros_wrapper_node-1] GNSS Port: 10110
[hesai_ros_wrapper_node-1] Rotation Speed: 600
[hesai_ros_wrapper_node-1] Sync Angle: 0
[hesai_ros_wrapper_node-1] Cut Angle: 0
[hesai_ros_wrapper_node-1] FoV Start: 0
[hesai_ros_wrapper_node-1] FoV End: 360
[hesai_ros_wrapper_node-1] Dual Return Distance Threshold: 0.1
[hesai_ros_wrapper_node-1] Calibration Path: /home/user/rosws/install/nebula_decoders/share/nebula_decoders/calibration/hesai/PandarXT16.csv
[hesai_ros_wrapper_node-1] PTP Profile: IEEE_1588v2
[hesai_ros_wrapper_node-1] PTP Domain: 0
[hesai_ros_wrapper_node-1] PTP Transport Type: UDP/IP
[hesai_ros_wrapper_node-1] PTP Switch Type: TSN
[hesai_ros_wrapper_node-1] [INFO] [1732770490.919631861] [hesai_ros_wrapper_node]: UDP-only mode is enabled. Settings checks, synchronization, and diagnostics publishing are disabled.
[hesai_ros_wrapper_node-1] [INFO] [1732770490.920580897] [IoContext::IoContext]: Thread(s) Created: 1
[hesai_ros_wrapper_node-1] [INFO] [1732770490.922213526] [hesai_ros_wrapper_node.HesaiDecoder]: Using calibration data from /home/user/rosws/install/nebula_decoders/share/nebula_decoders/calibration/hesai/PandarXT16.csv
[hesai_ros_wrapper_node-1] [INFO] [1732770490.922249846] [hesai_ros_wrapper_node.HesaiDecoder]: Starting Decoder
[hesai_ros_wrapper_node-1] [INFO] [1732770490.970740425] [hesai_ros_wrapper_node.HesaiDecoder]: . Wrapper=OK
[hesai_ros_wrapper_node-1] [INFO] [1732770490.971526867] [hesai_ros_wrapper_node.HwInterface]: Starting UDP receiver
[hesai_ros_wrapper_node-1] [WARN] [1732770492.015865025] [hesai_ros_wrapper_node]: New subscription discovered on topic '/pandar_points', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
```

The following output is from the /pandar_points topic.

```
$ros2 topic echo /pandar_points

---
header:
  stamp:
    sec: 1564025028
    nanosec: 99723008
  frame_id: hesai
height: 1
width: 16795
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
- name: intensity
  offset: 12
  datatype: 2
  count: 1
- name: return_type
  offset: 13
  datatype: 2
  count: 1
- name: channel
  offset: 14
  datatype: 4
  count: 1
- name: azimuth
  offset: 16
  datatype: 7
  count: 1
- name: elevation
  offset: 20
  datatype: 7
  count: 1
- name: distance
  offset: 24
  datatype: 7
  count: 1
- name: time_stamp
  offset: 28
  datatype: 6
  count: 1
is_bigendian: false
point_step: 32
row_step: 537440
data:
- 179
- 7
- 154
- '...'
is_dense: true
---
```

I'm trying to visualize this in rviz but initially it was saying no actual frame map.  I tried publishing static tf from map to hesai but still  can't see any data on rviz. Can you please help with this?
